plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - optymo-reverse-engineering-part-1.md
  - optymo-reverse-engineering-part-2.md
  - optymo-reverse-engineering-part-3.md