name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
  apk:
    name: Generate and release APK
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload release
        uses: yakuhzi/action-release@v1
        with:
          file: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  assemble_job:
    name: Assemble
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: Restore Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Assemble Debug
          run: ./gradlew assembleDebug

        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: apk
            path: app/build/outputs/apk/debug/**.apk